"use client";
import Link from "next/link";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ArrowLeft, CalendarDays, ShoppingBasket } from "lucide-react";

const days = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"];
const menus = [["Avena · yogur · plátano", "Pollo · arroz · verduras", "Salmón · patata · ensalada"], ["Tostada · aguacate · huevo", "Lentejas · huevo · ensalada", "Merluza · calabacín · patata"], ["Kéfir · frutos rojos · nueces", "Pavo · quinoa · verduras", "Crema de verduras · tortilla"], ["Porridge · manzana · canela", "Garbanzos · arroz · espinacas", "Pollo · boniato · ensalada"], ["Yogur · avena · pera", "Pasta integral · atún · tomate", "Tofu · verduras · arroz"], ["Tostada · tomate · queso fresco", "Arroz · salmón · brócoli", "Ensalada completa · huevo"], ["Avena · kiwi · almendras", "Pollo · patata · verduras", "Crema · pescado blanco · pan integral"]];
export default function WeeklyPlanPage(){const [changed,setChanged]=useState<number[]>([]);const toggle=async(index:number)=>{setChanged(value=>value.includes(index)?value.filter(x=>x!==index):[...value,index]);const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const start=new Date();start.setDate(start.getDate()-((start.getDay()+6)%7));const week=start.toISOString().slice(0,10);const {data:plan}=await supabase.from("weekly_plans").upsert({user_id:user.id,week_start:week},{onConflict:"user_id,week_start"}).select("id").single();if(plan){const date=new Date(start);date.setDate(date.getDate()+index);await supabase.from("weekly_plan_meals").upsert({plan_id:plan.id,plan_date:date.toISOString().slice(0,10),meal_type:"lunch",title:"Menú regenerado",foods:["Propuesta personalizada"],grams:{},kcal:1850},{onConflict:"plan_id,plan_date,meal_type"});}};return <main className="min-h-screen bg-[#F8F7F3] px-5 py-6 text-[#25342D] sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/nutrition" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-[#267C60]"><ArrowLeft size={17}/> Volver a nutrición</Link><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-[#267C60]"><CalendarDays size={17}/> Planificación</p><h1 className="text-3xl font-black sm:text-4xl">Tu menú semanal</h1><p className="mt-2 text-[#5B6B63]">Organiza tus comidas y tu compra con antelación.</p></div><Link href="/shopping-list" className="inline-flex items-center gap-2 rounded-xl bg-[#267C60] px-4 py-3 text-sm font-bold text-white"><ShoppingBasket size={17}/> Ver lista de la compra</Link></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{days.map((day,index)=><article key={day} className="rounded-3xl border border-[#E6E3DD] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{day}</h2><span className="rounded-full bg-[#DFF3E8] px-3 py-1 text-xs font-bold text-[#267C60]">1.850 kcal</span></div><div className="mt-5 space-y-3">{["Desayuno","Comida","Cena"].map((meal,mealIndex)=><div key={meal} className="rounded-2xl bg-[#F8F7F3] p-3"><p className="text-xs font-bold uppercase tracking-widest text-[#718078]">{meal}</p><p className="mt-1 text-sm font-bold">{changed.includes(index) ? ["Tostada integral · aguacate · huevo","Garbanzos · quinoa · verduras","Tofu · patata · ensalada"][mealIndex] : menus[index][mealIndex]}</p><p className="mt-1 text-xs text-[#267C60]">{mealIndex===0?"60 g + 150 g + 120 g":mealIndex===1?"150 g + 180 g + 200 g":"150 g + 180 g + 150 g"}</p></div>)}</div><button onClick={()=>toggle(index)} className="mt-4 w-full rounded-xl border border-[#C8E7D8] py-2.5 text-sm font-bold text-[#267C60]">{changed.includes(index)?"Restaurar día":"Cambiar día"}</button></article>)}</div></div></main>}
