import Link from "next/link";
import { Activity, Apple, ArrowUpRight, Check, Dumbbell, HeartPulse, Leaf, Target } from "lucide-react";

const modules = [
  { icon: Apple, title: "Nutrición", text: "Registra tus comidas y observa tus macros con claridad." },
  { icon: Activity, title: "Movimiento", text: "Cardio y fuerza en un mismo lugar, a tu ritmo." },
  { icon: HeartPulse, title: "Tu cuerpo", text: "Sigue tus medidas y evolución sin juicios." },
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-cream">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-10"><div className="flex items-center gap-2 text-xl font-bold tracking-tight"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sage-500 text-white"><Leaf size={19} /></span> Wellyo</div><Link href="/login" className="rounded-full border border-sage-200 bg-white px-5 py-2 text-sm font-semibold text-ink shadow-sm">Entrar</Link></nav>
    <section className="mx-auto grid max-w-6xl gap-12 px-6 pb-20 pt-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-16"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full bg-sage-100 px-4 py-2 text-sm font-semibold text-sage-700"><span className="h-2 w-2 rounded-full bg-sage-500" /> Tu bienestar. A tu manera.</div><h1 className="max-w-xl text-5xl font-bold leading-[1.05] tracking-[-.04em] text-ink sm:text-6xl">Pequeños pasos.<br /><span className="text-sage-500">Bienestar real.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-ink/65">Un espacio sencillo para entender tus hábitos, celebrar tu constancia y construir una rutina que encaje contigo.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-xl bg-sage-500 px-6 py-3.5 font-semibold text-white shadow-soft transition hover:bg-sage-700">Crear mi espacio <ArrowUpRight size={18} /></Link><button className="rounded-xl border border-sage-200 bg-white px-6 py-3.5 font-semibold text-ink">Conocer Wellyo</button></div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute -right-12 -top-10 h-40 w-40 rounded-full bg-lilac/70 blur-2xl" /><div className="relative rounded-[2rem] border border-white bg-white p-5 shadow-soft"><div className="rounded-[1.5rem] bg-sage-50 p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-ink/55">Tu resumen de hoy</p><p className="mt-1 text-2xl font-bold">Un día a la vez</p></div><div className="rounded-xl bg-lilac p-2 text-sage-500"><Target size={20} /></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4"><p className="text-xs text-ink/50">Constancia</p><p className="mt-2 text-2xl font-bold">82%</p><div className="mt-3 h-1.5 rounded-full bg-sage-100"><div className="h-full w-4/5 rounded-full bg-sage-500" /></div></div><div className="rounded-2xl bg-white p-4"><p className="text-xs text-ink/50">Hábitos</p><p className="mt-2 text-2xl font-bold">4/5</p><div className="mt-3 flex gap-1">{[1,2,3,4,5].map(i => <span key={i} className={`h-5 w-5 rounded-full ${i < 5 ? "bg-sage-500" : "bg-sage-100"}`}><Check size={13} className="m-auto mt-1 text-white" /></span>)}</div></div></div><div className="mt-3 rounded-2xl bg-white p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Esta semana</p><span className="text-xs text-sage-700">+12%</span></div><div className="mt-5 flex h-20 items-end justify-between gap-2">{[35,52,44,68,58,82,62].map((height,i) => <div key={i} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-lg ${i === 5 ? "bg-sage-500" : "bg-sage-200"}`} style={{height: `${height}%`}} /><span className="text-[10px] text-ink/45">{["L","M","X","J","V","S","D"][i]}</span></div>)}</div></div></div></div></div></section>
    <section className="mx-auto max-w-6xl px-6 pb-24 lg:px-10"><div className="mb-8 flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-sage-500">Todo en un mismo lugar</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Conoce tu propio ritmo</h2></div><Dumbbell className="hidden text-sage-200 sm:block" size={42} /></div><div className="grid gap-4 md:grid-cols-3">{modules.map(({icon: Icon,title,text}) => <article key={title} className="rounded-3xl border border-sage-100 bg-white p-6 shadow-sm"><div className="mb-8 flex h-11 w-11 items-center justify-center rounded-2xl bg-sage-100 text-sage-700"><Icon size={21} /></div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-ink/60">{text}</p></article>)}</div></section>
  </main>;
}
