"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Apple, ArrowLeft, Check, ChevronRight, Info, Leaf, RefreshCw, Target } from "lucide-react";

const recommendations = [
  { title: "Desayuno", time: "08:00", kcal: 420, items: ["Avena con yogur natural", "Plátano y nueces"], color: "#DFF3E8" },
  { title: "Comida", time: "14:00", kcal: 680, items: ["Bowl de arroz integral", "Pollo, aguacate y verduras"], color: "#EAE4FA" },
  { title: "Snack", time: "17:30", kcal: 210, items: ["Hummus", "Zanahoria y pan integral"], color: "#F4EBD9" },
  { title: "Cena", time: "21:00", kcal: 540, items: ["Salmón al horno", "Patata y ensalada verde"], color: "#DFF3E8" },
];

export default function NutritionPage() {
  const [planSeed, setPlanSeed] = useState(0);
  const plan = recommendations.map((meal, index) => planSeed % 2 === 0 ? meal : { ...meal, items: index === 0 ? ["Tostada integral con aguacate", "Huevo y fruta de temporada"] : index === 1 ? ["Lentejas con verduras", "Ensalada de tomate y aceite de oliva"] : index === 2 ? ["Kéfir natural", "Almendras y manzana"] : ["Crema de calabacín", "Tortilla francesa y pan integral"] });
  const [targets, setTargets] = useState({ calories: 1850, protein: 105, carbs: 210, fat: 60 });
  const [goalLabel, setGoalLabel] = useState("Sentirte con más energía");
  useEffect(() => { (async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from("user_goals").select("calorie_target, protein_target, carbohydrate_target, fat_target").eq("user_id", user.id).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (data) setTargets({ calories: data.calorie_target ?? 1850, protein: data.protein_target ?? 105, carbs: data.carbohydrate_target ?? 210, fat: data.fat_target ?? 60 }); })(); }, []);
  return <main className="min-h-screen bg-[#F8F7F3] px-5 py-6 text-[#25342D] sm:px-8"><div className="mx-auto max-w-5xl">
    <Link href="/dashboard" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-[#267C60]"><ArrowLeft size={17}/> Volver al inicio</Link>
    <header className="mb-8 flex items-start justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-[#267C60]"><Apple size={17}/> Nutrición</p><h1 className="text-3xl font-black sm:text-4xl">Tu plan para hoy</h1><p className="mt-2 text-[#5B6B63]">Propuestas sencillas adaptadas a tu objetivo y a tu ritmo.</p></div><div className="hidden rounded-2xl bg-[#DFF3E8] p-4 text-[#267C60] sm:block"><Leaf size={28}/></div></header>
    <section className="mb-8 rounded-3xl bg-[#267C60] p-6 text-white shadow-sm"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-[#DFF3E8]">Objetivo actual</p><h2 className="mt-1 text-2xl font-black">{goalLabel}</h2><button className="mt-3 text-sm font-bold text-white/80 underline underline-offset-4">Cambiar objetivo</button></div><div className="flex items-center gap-4"><div className="relative flex h-24 w-24 items-center justify-center rounded-full border-8 border-white/20"><span className="text-xl font-black">0%</span></div><div className="text-sm text-white/80"><p>0 de {targets.calories} kcal</p><p className="mt-1">Plan del día</p></div></div></div></section>
    <div className="mb-6 flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-[#267C60]">Recomendado para ti</p><h2 className="mt-1 text-2xl font-black">Tu día, paso a paso</h2></div><button onClick={() => setPlanSeed(planSeed + 1)} className="inline-flex items-center gap-2 rounded-xl border border-[#C8E7D8] bg-white px-3 py-2 text-sm font-bold text-[#267C60]"><RefreshCw size={15}/> Regenerar</button></div>
    <section className="grid gap-4 sm:grid-cols-2">{plan.map((meal) => <article key={meal.title} className="rounded-3xl border border-[#E6E3DD] bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#718078]">{meal.time}</p><h3 className="mt-1 text-xl font-black">{meal.title}</h3></div><span className="rounded-full px-3 py-1 text-xs font-bold text-[#315E4C]" style={{backgroundColor:meal.color}}>{meal.kcal} kcal</span></div><div className="mt-5 space-y-2">{meal.items.map((item) => <div key={item} className="flex items-center gap-2 text-sm text-[#53645B]"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#DFF3E8] text-[#267C60]"><Check size={13}/></span>{item}</div>)}</div><div className="mt-5 flex gap-2"><button className="flex-1 rounded-xl bg-[#267C60] py-3 text-sm font-bold text-white">Añadir al día</button><button className="rounded-xl border border-[#D9E8DF] px-3 text-[#267C60]" aria-label={`Cambiar ${meal.title}`}><RefreshCw size={16}/></button></div></article>)}</section>
    <section className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-[#E6E3DD] bg-white p-5"><div className="flex items-center gap-2 text-[#267C60]"><Target size={18}/><h2 className="font-black">Cómo va tu objetivo</h2></div><div className="mt-5 space-y-4 text-sm"><div><div className="mb-1 flex justify-between"><span>Proteínas</span><b>0 / {targets.protein} g</b></div><div className="h-2 rounded-full bg-[#DFF3E8]"><div className="h-full w-0 rounded-full bg-[#267C60]"/></div></div><div><div className="mb-1 flex justify-between"><span>Carbohidratos</span><b>0 / {targets.carbs} g</b></div><div className="h-2 rounded-full bg-[#EAE4FA]"><div className="h-full w-0 rounded-full bg-[#8D79C5]"/></div></div></div></div><div className="rounded-3xl border border-[#C8E7D8] bg-[#DFF3E8] p-5"><div className="flex gap-3 text-sm text-[#315E4C]"><Info size={18} className="shrink-0"/><p>Las propuestas son orientativas. Puedes cambiar cualquier alimento y ajustar las cantidades a tus preferencias.</p></div><button className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#267C60]">Personalizar preferencias <ChevronRight size={16}/></button></div></section>
    <p className="mt-8 text-center text-xs text-[#718078]">Las sugerencias se enriquecerán con tus preferencias, historial y catálogo de Open Food Facts.</p>
  </div></main>;
}
